PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?piece ?velocity ?note
FROM <http://purl.org/midi-ld/doremus>
WHERE {
    ?piece a mid:Piece; mid:hasTrack ?track .
    ?track mid:hasEvent ?startev, ?endev .
    ?startev a mid:NoteOnEvent .
    OPTIONAL {
        ?startev mid:velocity ?o
         BIND (CONCAT('vel:',xsd:integer(ROUND(?o/10))) AS ?velocity) # integer
    }
    ?startev mid:note ?note ; mid:tick ?startTick .
    ?endev a mid:NoteOffEvent ; mid:note ?note ; mid:tick ?endTick .
}