PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?piece ?event
FROM <http://purl.org/midi-ld/doremus>
WHERE {
    # VALUES ?piece {<http://purl.org/midi-ld/pattern/7a6e0863caf80b1f932bbd8249c9be91>}
    ?piece a mid:Piece; mid:hasTrack / mid:hasEvent ?event .
}
# LIMIT 100


