PREFIX mid: <http://purl.org/midi-ld/midi#>

SELECT DISTINCT ?piece ?bpmm
FROM <http://purl.org/midi-ld/doremus>
WHERE {
    ?piece a mid:Piece; mid:hasTrack / mid:hasEvent ?event .
    ?event a mid:SetTempoEvent .
    OPTIONAL {
         ?event mid:bpm ?bpm .  # double
         BIND (CONCAT('bpm:',xsd:integer(ROUND(?bpm/10))) AS ?bpmm) # integer
    }
}